project:
  type: website
  output-dir: docs

website:
  title: "Katie Knox - MCP Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs
        text: MUSA 5080 Assignments
        
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    embed-resources: true

execute:
  freeze: auto
